### ISSUE TITLE
Different kind of obstacles

### ISSUE THREAD

**Issue by dvberkel** [AJFaraday/grid_game#2]
I would like to see different kind of obstacles. I am thinking of 

* mountains that are indestructible
* marshes that would low soldiers down

**Comment by AJFaraday** [comment]
I'm still not sure how I am going to achieve any of this, but I've had an idea and this seemed like the best place to put it.

**Walls** - A wall has a set health, probably 5. It's impassable, until this health is depleted, but doesn't attack back like soldiers do.

Question is, does a wall take damage every turn? Here's the problem

|t1| | |1| |W5| 
|t2|1| | |1|W4|
|t3| |1| | 1|W3|
|t4| | |1|1|W2| 
|t5| | | |2|W0|

This way, it doesn't seem to allow much grouping until the wall falls. Perhaps a group of walls together.

**Comment by dvberkel** [comment]
Good questions. I will reflect on this before I come back to you

**Comment by AJFaraday** [comment]
*Idea:* A city will clear the adjacent land, removing all adjacent obstacles. This means that building a city against, say, a mountain, would remove it as an option for the opponent to build against.

Pros:
* This adds a new mini-goal, to build those strategically important centre board cities first.
* It prevents un-finishable game scenarios, created by random board generation.

Cons:
* This may weaken the value of impassable obstacles in a game design scenario.

**Comment by AJFaraday** [comment]
I've implemented the simplest obstacle type, rocks (completely impassable, randomly placed) in this PR https://github.com/AJFaraday/grid_game/pull/7

**Comment by AJFaraday** [comment]
The initial 'rocks' use-case can now be tested at www.right-twix.com

**Comment by AJFaraday** [comment]
I've implemented the initial, simplest obstacle, 'rocks', which will act as a pattern for the others.

Other obstacle types are now logged as #11 and #12.

I'm closing this issue to continue further work on those tickets.

Thanks again @dvberkel for taking an interest in the project.
