### ISSUE TITLE
[quick feature request] Tick speed editor

### ISSUE THREAD

**Issue by Uchiha-Senju** [AJFaraday/grid_game#28]
There should be a sort of slide bar/number field to modulate the number of ticks per second. Bot v. Bot is faster than the normal but sometimes it is not fast enough (e.g. Fcage v. Fcage)

**Comment by AJFaraday** [comment]
New usability features:

* Game speed slider
* 'One Step' button
* Direction changes while the game is paused (key input from manual bots) will take the game forward one step
