### ISSUE TITLE
Grid/table rendering in firefox

### ISSUE THREAD

**Issue by 1bpm** [AJFaraday/grid_game#3]
Firefox 31 presents the grid/table to the far right of the page and seems to reduce the column width to a minimum when a column doesn't contain anything.

**Comment by AJFaraday** [comment]
I've tried this with Firefox 47, on a recent install of Linux Mint, and I'm not seeing this issue.

![image](https://cloud.githubusercontent.com/assets/237798/17748970/ce7bea90-6489-11e6-895b-be177fe1dedd.png)

Without reproducing the issue, I probably can't find a fix for it.

You may be able to work around this issue by updating Firefox.
